import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Harsh Rajput",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css?family=Heebo:300,400,500,700&display=swap"
          rel="preload stylesheet"
          as="style"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,800,900,1000&display=swap"
          rel="preload stylesheet"
          as="style"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Farro:300,400,500,700&display=swap"
          rel="preload stylesheet"
          as="style"
        />
         <link
          href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&display=swap"
          rel="preload stylesheet"
          as="style"
        />
        <link href="https://fonts.googleapis.com/css2?family=Anek+Malayalam:wght@100..800&family=Space+Grotesk:wght@300..700&display=swap" rel="stylesheet"></link>

        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
